# model
model_name: "klue/roberta-base"
batch_size: 32
num_workers: 4

# trainer
ngpu: 1
max_epochs: 200
check_val_every_n_epoch: 2
accumulate_grad_batches: 1
log_every_n_steps: 100

# wandb logger
project: RL