# trainer
gpu: "cpu"
net_name: "PolicyGradient"
checkpoint_path: "checkpoint/PolicyGradient/last-v1.ckpt"


model:
  model_name: "klue/roberta-base"
  batch_size: 32
  num_workers: 8
  net:
    policy_net:
      _target_: network.PolicyNet
      model_name: ${model.model_name}
      num_classes: 10
    value_net:
      _target_: network.Classifier
      model_name: ${model.model_name}
      num_classes: ${model.net.policy_net.num_classes}
    gamma: 0.9

  # optimizer
  lr: 5e-5

  # model sync rate
  sync_rate: 10

  # eps
  eps_start: 1.0
  eps_end: 0.01

  # to populate
  initial_eps: 1.0

  gpu: ${gpu}

# seed
seed: 9999

# wandb logger
project: RL
name: DQN_dueling